on:
  push:
    branches: ["master"]

permissions:
  contents: write

env:
  EM_VERSION: 3.1.34
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build-publish-windows:
    name: Build Windows
    concurrency: ci-windows-${{ github.ref }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Add MSBUILD to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: msbuild Windows\Cubic.vcxproj -t:rebuild -property:Configuration=Release -property:Platform=x64

      - name: Publish
        run: |
          cd Windows\x64\Release
          tar.exe -a -c -f Cubic_Windows_x64.zip Cubic.exe SDL2.dll glew32.dll
      
  build-deploy-web:
    name: Build and Deploy
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
        
      - name: Install Emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Build
        run: |
          cd Web
          make -j4
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Web/Build
