name: Build and Publish (windows)

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-windows-${{ github.ref }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build
        run: |
          cd Windows
          msbuild Cubic.sln /p:Configuration=Release

      - name: Compress
        run: |
          copy Windows\Libraries\SDL2.dll .
          copy Windows\Libraries\glew32.dll .
          copy Windows\x64\Release\Cubic.exe .
          tar.exe -a -c -f Cubic.zip Cubic.exe glew32.dll SDL2.dll
          
      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Cubic.zip
          asset_name: Cubic.zip
          tag: Stable
          overwrite: true